port: 8080
app:
  name: test
  version: 1.0.0
  env: dev
log:
  level: DEBUG
jwt:
  secret: 123456
  exp: 7
database:
  mysql:
    host: localhost
    port: 3306
    db: ticket_system
    username: root
    password: 
    maxIdleConns: 10
    maxOpenConns: 100
  redis:
    host: localhost
    port: 6379
    password: 123456
    db: 0
    poolSize: 10
